import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Miau-Juda",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        {/* Colocar as imagens no storage do supabase e mudar aqui */}
        {/* usar o link no lugar do a href para mudar de páginas */}


        <header>
            <div className="imgs-header">
            <img src="../imgs/miaujuda/Dog1-mascara.png" alt="dog1" id="dog1" />
            <img src="../imgs/miaujuda/Logo-miaujuda.png" alt="logo" id="logo" />
            </div>
            <div className="options">

            <a href="">Miau-Dota</a>
            <a href="">Perdi meu pet</a>
            <a href="">Achei um pet</a>
            <a href="">
                <img
                src="../imgs/miaudota/user-base.png"
                alt="base-user-profile"
                id="user"
                />
                </a>

            </div>
        </header>

        {children}

        <footer>
            <img className="logo-footer" src="../imgs/miaujuda/logo-footer-juda.png" /> 
            <div className="infos-pag">
                Entre em contato <br />
                Miaujuda@miauau.com
            </div>
        </footer>
      </body>
    </html>
  );
}
